# Generated by Django 2.2.16 on 2020-09-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
