# Generated by Django 2.2.16 on 2020-09-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_demo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
