# Generated by Django 2.2.16 on 2020-09-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="demo",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
