# Generated by Django 2.2.16 on 2020-09-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_cars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
