# Generated by Django 2.2.16 on 2020-09-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
