# Generated by Django 2.2.16 on 2020-09-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_delete_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Std",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asdfsdf", models.BigIntegerField()),
            ],
        ),
    ]
