# Generated by Django 2.2.16 on 2020-09-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_std"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Std",
        ),
    ]
