# Generated by Django 2.2.16 on 2020-09-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_delete_newmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.BigIntegerField()),
            ],
        ),
    ]
