# Generated by Django 2.2.16 on 2020-09-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_books"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Books",
        ),
    ]
